services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: municipal_revenue_python
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.example
    depends_on:
      - hive-server
    command: python --version

  spark-master:
    image: apache/spark:4.0.3-python3
    container_name: municipal_revenue_spark_master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080

  spark-worker:
    image: apache/spark:4.0.3-python3
    container_name: municipal_revenue_spark_worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --webui-port 8081

  hive-metastore:
    image: apache/hive:4.1.0
    container_name: municipal_revenue_hive_metastore
    hostname: hive-metastore
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
    volumes:
      - hive-warehouse:/opt/hive/data/warehouse

  hive-server:
    image: apache/hive:4.1.0
    container_name: municipal_revenue_hive_server
    hostname: hive-server
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://hive-metastore:9083"
    volumes:
      - hive-warehouse:/opt/hive/data/warehouse
      - .:/app

volumes:
  hive-warehouse:
